# Generated by Django 4.1.7 on 2023-02-26 13:32

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
    ]
