# Generated by Django 4.1.7 on 2023-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_view',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
